const y8Urls = {
  '/y8-studio/unity/Ankit/tunnel_rush/': 'https://www.y8.com/games/tunnel_rush',
  '/y8-studio/unity/akeemywka/death_squad_the_last_mission/': 'https://www.y8.com/games/death_squad_the_last_mission',
  '/y8-studio/unity/akeemywka/getaway_shootout/': 'https://www.y8.com/games/getaway_shootout',
  '/y8-studio/unity/akeemywka/hide_online/': 'https://www.y8.com/games/hide_online',
  '/y8-studio/unity/akeemywka/impossible_bike_stunts_3d/': 'https://www.y8.com/games/impossible_bike_stunt_3d',
  '/y8-studio/unity/akeemywka/last_resistance_city_under_siege/': 'https://www.y8.com/games/last_resistance_-_city_under_siege',
  '/y8-studio/unity/akeemywka/leader_strike/': 'https://www.y8.com/games/leader_strike',
  '/y8-studio/unity/akeemywka/masked_forces/': 'https://www.y8.com/games/masked_forces',
  '/y8-studio/unity/akeemywka/moto_trials_winter/': 'https://www.y8.com/games/moto_trials_winter',
  '/y8-studio/unity/akeemywka/moto_trials_winter_2/': 'https://www.y8.com/games/moto_trials_winter_2',
  '/y8-studio/unity/akeemywka/parkour_go_2/': 'https://www.y8.com/games/parkour_go_2_urban',
  '/y8-studio/unity/akeemywka/prop_busters/': 'https://www.y8.com/games/prop_busters',
  '/y8-studio/unity/akeemywka/rooftop_snipers/': 'https://www.y8.com/games/rooftop_snipers',
  '/y8-studio/unity/akeemywka/russian_extreme_offroad/': 'https://www.y8.com/games/russian_extreme_offroad',
  '/y8-studio/unity/akeemywka/stained_act_1/': 'https://www.y8.com/games/stained_act_1',
  '/y8-studio/unity/akeemywka/stunt_racers_extreme/': 'https://www.y8.com/games/stunt_racers_extreme',
  '/y8-studio/unity/akeemywka/stunt_racers_extreme_2/': 'https://www.y8.com/games/stunt_racers_extreme_2',
  '/y8-studio/unity/akeemywka/taz_mechanic_simulator/': 'https://www.y8.com/games/taz_mechanic_simulator',
  '/y8-studio/unity/akeemywka/truck_driver_crazy_road_2/': 'https://www.y8.com/games/truck_driver_crazy_road_2',
  '/y8-studio/unity/akeemywka/voxel_front_3d/': 'https://www.y8.com/games/voxel_front_3d',
  '/y8-studio/unity/joll/crime_city_3d/': 'https://www.y8.com/games/crime_city_3d',
  '/y8-studio/unity/joll/freefall_tournament/': 'https://www.y8.com/games/freefall_tournament',
  '/y8-studio/unity/joll/military_wars_3d_multiplayer/': 'https://www.y8.com/games/military_wars_3d_multiplayer',
  '/y8-studio/unity/joll/rocking_sky_trip/': 'https://www.y8.com/games/rolling_sky_trip',
  '/y8-studio/unity/joll/russian_car_driver_hd/': 'https://www.y8.com/games/russian_car_driver_hd',
  '/y8-studio/unity/joll/slope/': 'https://www.y8.com/games/slope',
}
